version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "testValue1"
#     "major_version" : "5"
    #"minor_version" : "2"
#   exportedVariables:
#     - testEnv
#     - major_version
    #- minor_version
steps:
  - type: Command
    timeoutInSeconds: 400
    name: "trtdtd"
    command: |
      export testEnv=123
      echo $testEnv > output1.txt

outputArtifacts:
  - name: output2
    type: BINARY
    location: output1.txt
#   - name: output
#     type: BINARY
#     location: src/main/java/org/example/output.txt
#   - name: hello-dev-jar
#     type: BINARY
#     artifactParams:
#       testKey: testVal
#       testKey1: ${testEnv}
#       testKey2: ${invalidVar}
#     location: src/main/java/org/example/HelloWorld.class
#   - name: hello-dev-image
#     type: DOCKER_IMAGE
#     location: iad.ocir.io/id204we8d65n/balaregistry/hello-bala:1.0
