version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "testEnv" : "Hello, This is a test variable!!!"
    "VERS" : 20.0
  vaultVariables:
    gl_tok: ocid1.vaultsecret.oc1.iad.amaaaaaa34lgq7aam4mnjel4gfp76bug3uxnjscsxpzxyrjqqxosdjhkpuaq
  exportedVariables:
    - VERS
 

steps:
  - type: Command
    name: "PreReq install"
    command: |
      yum -y install curl
  - type: Command
    name: "Dockerize"
    command: |
      docker build . --tag docktest:1.0
  - type: Command
    name: "Run the app Locally"
    command: |
      docker run -d -p 5000:5000 --name docktest docktest:1.0
  - type: Command
    name: "Shutdown the app"
    command: |
      docker stop docktest >> docktest_result.txt
      docker save -o hello-test_1.0.tar docktest:1.0
      docker rm docktest >> docktest_result.txt
      date >> docktest_result.txt
      echo ${gl_tok} >> docktest_result.txt
outputArtifacts:
  - name: docktest_result
    type: BINARY
    location: docktest_result.txt
    artifactParams:
      testEnv: ${testEnv}
      vers: 1.0
      
# version: 0.1
# component: build
# timeoutInSeconds: 600
# runAs: root
# shell: bash
# env:
#   variables:
# #     "version" : "3.4"
#     "repoName": "docktest"
#     "major_version": "4"
#     "minor_version": "4"
    
#   exportedVariables:
#     - minor_version
# #     - version
#     - major_version
#     - repoName

# steps:
#   - type: Command
#     name: "PreReq install"
#     command: |
#       yum -y install curl
#   - type: Command
#     name: "Dockerize"
#     command: |
#       docker build -t docktest .
#   - type: Command
#     name: "Save"
#     command: |
#       docker save docktest -o docktest.tar
#   - type: Command
#     name: "SaveResult"
#     command: |
#       ls >> dockImagesResult.txt
# #   - type: Command
# #     name: "SaveResult"
# #     command: |
# #       export major_version=1.2

# outputArtifacts:
#   - name: docktest    # Eg: foo-java-app
#     type: BINARY     # Enum: [BINARY, DOCKER_IMAGE]
#     location: docktest.tar 
#   - name: docktestimage    # Eg: foo-java-app
#     type: DOCKER_IMAGE     # Enum: [BINARY, DOCKER_IMAGE]
#     location: docktest
